/*
* ----------------------------------------------------
* @author: 4quarenta
* @author URI: https://github.com/4quarenta
* @copyright: (c) 2026 ConcursoMestre. All rights reserved
* ----------------------------------------------------
*
* @since 1.0.0
*
*/

import type {
  GamificationRuleSettings,
  GamificationSettings,
  NotificationRuleSettings,
  NotificationSettings,
} from '@types';

const normalizeBoolean = (value: unknown, fallback: boolean): boolean => {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'number') return value !== 0;
  if (typeof value === 'string') {
    const normalized = value.trim().toLowerCase();
    if (['1', 'true', 'yes', 'on'].includes(normalized)) return true;
    if (['0', 'false', 'no', 'off', ''].includes(normalized)) return false;
  }

  return fallback;
};

export const DEFAULT_GAMIFICATION_RULES: GamificationRuleSettings[] = [
  {
    key: 'answer_correct',
    eventName: 'answer_correct',
    category: 'Pratica',
    label: 'Acerto em questao',
    description: 'Recompensa principal quando o aluno acerta uma questao.',
    xp: 10,
    reputation: 0,
    repeatability: 'Por resposta correta',
    enabled: true,
  },
  {
    key: 'answer_incorrect_reviewed',
    eventName: 'answer_incorrect_reviewed',
    category: 'Pratica',
    label: 'Erro revisado',
    description: 'Recompensa pequena para manter o erro como parte do estudo.',
    xp: 2,
    reputation: 0,
    repeatability: 'Por revisao valida',
    enabled: true,
  },
  {
    key: 'question_saved_for_review',
    eventName: 'question_saved_for_review',
    category: 'Pratica',
    label: 'Questao salva',
    description: 'Quando o aluno salva uma questao para revisar depois.',
    xp: 3,
    reputation: 0,
    repeatability: 'Uma vez por questao',
    enabled: true,
  },
  {
    key: 'daily_study_activity',
    eventName: 'daily_study_activity',
    category: 'Constancia',
    label: 'Estudo do dia',
    description: 'Atividade diaria registrada em questoes.',
    xp: 5,
    reputation: 0,
    repeatability: 'Uma vez por dia',
    enabled: true,
  },
  {
    key: 'study_streak_milestone',
    eventName: 'study_streak_milestone',
    category: 'Constancia',
    label: 'Marcos de sequencia',
    description: 'Bonus de 3, 7, 15 e 30 dias seguidos.',
    xp: 15,
    maxXp: 250,
    reputation: 1,
    repeatability: 'Por marco alcancado',
    enabled: true,
  },
  {
    key: 'answer_progress_milestone',
    eventName: 'answer_progress_milestone',
    category: 'Marcos',
    label: 'Questoes respondidas e acertos',
    description: 'Bonus por volume de respostas e acertos acumulados.',
    xp: 25,
    maxXp: 150,
    reputation: 0,
    repeatability: 'Por marco alcancado',
    enabled: true,
  },
  {
    key: 'simulation_completed',
    eventName: 'simulation_completed',
    category: 'Simulados',
    label: 'Simulado concluido',
    description: 'XP calculado por conclusao, volume respondido e acertos.',
    xp: 15,
    maxXp: 85,
    reputation: 1,
    repeatability: 'Uma vez por simulado',
    enabled: true,
  },
  {
    key: 'comment_submitted',
    eventName: 'comment_submitted',
    category: 'Comunidade',
    label: 'Comentario enviado',
    description: 'Comentario publicado ou enviado para moderacao.',
    xp: 3,
    reputation: 0,
    repeatability: 'Por comentario valido',
    enabled: true,
  },
  {
    key: 'comment_reply_submitted',
    eventName: 'comment_reply_submitted',
    category: 'Comunidade',
    label: 'Resposta em comentario',
    description: 'Resposta enviada em uma conversa de comentarios.',
    xp: 2,
    reputation: 0,
    repeatability: 'Por resposta valida',
    enabled: true,
  },
  {
    key: 'comment_auto_approved',
    eventName: 'comment_auto_approved',
    category: 'Comunidade',
    label: 'Comentario publicado automaticamente',
    description: 'Comentario que ficou visivel sem fila de moderacao.',
    xp: 5,
    reputation: 1,
    repeatability: 'Por comentario',
    enabled: true,
  },
  {
    key: 'comment_approved',
    eventName: 'comment_approved',
    category: 'Comunidade',
    label: 'Comentario aprovado pela moderacao',
    description: 'Comentario liberado manualmente pela equipe.',
    xp: 10,
    reputation: 1,
    repeatability: 'Por comentario aprovado',
    enabled: true,
  },
  {
    key: 'comment_like_received',
    eventName: 'comment_like_received',
    category: 'Comunidade',
    label: 'Curtida recebida',
    description: 'Quando outro aluno curte um comentario do usuario.',
    xp: 2,
    reputation: 1,
    repeatability: 'Por curtida unica',
    enabled: true,
  },
  {
    key: 'report_submitted',
    eventName: 'report_submitted',
    category: 'Moderacao',
    label: 'Denuncia enviada',
    description: 'Sinalizacao inicial de problema feita pelo aluno.',
    xp: 2,
    reputation: 0,
    repeatability: 'Por denuncia',
    enabled: true,
  },
  {
    key: 'report_accepted',
    eventName: 'report_accepted',
    category: 'Moderacao',
    label: 'Denuncia aceita',
    description: 'Quando a equipe confirma que a denuncia procedeu.',
    xp: 15,
    reputation: 1,
    repeatability: 'Por denuncia procedente',
    enabled: true,
  },
  {
    key: 'platform_rating_submitted',
    eventName: 'platform_rating_submitted',
    category: 'Suporte',
    label: 'Avaliacao da plataforma',
    description: 'Feedback estruturado sobre a plataforma.',
    xp: 20,
    reputation: 1,
    repeatability: 'Uma vez por avaliacao',
    enabled: true,
  },
  {
    key: 'suggestion_submitted',
    eventName: 'suggestion_submitted',
    category: 'Suporte',
    label: 'Sugestao enviada',
    description: 'Sugestao publica enviada para o mural.',
    xp: 8,
    reputation: 1,
    repeatability: 'Por sugestao',
    enabled: true,
  },
  {
    key: 'support_feedback_submitted',
    eventName: 'support_feedback_submitted',
    category: 'Suporte',
    label: 'Contato com suporte',
    description: 'Mensagem comum enviada pela central de suporte.',
    xp: 4,
    reputation: 0,
    repeatability: 'Por atendimento',
    enabled: true,
  },
  {
    key: 'support_thread_reply',
    eventName: 'support_thread_reply',
    category: 'Suporte',
    label: 'Resposta no suporte',
    description: 'Resposta enviada em conversa de suporte.',
    xp: 2,
    reputation: 0,
    repeatability: 'Por resposta',
    enabled: true,
  },
  {
    key: 'public_suggestion_vote',
    eventName: 'public_suggestion_vote',
    category: 'Suporte',
    label: 'Voto em sugestao publica',
    description: 'Like ou dislike em uma sugestao enviada por aluno.',
    xp: 1,
    reputation: 0,
    repeatability: 'Uma vez por sugestao',
    enabled: true,
  },
  {
    key: 'profile_photo_uploaded',
    eventName: 'profile_photo_uploaded',
    category: 'Perfil',
    label: 'Foto de perfil',
    description: 'Primeira foto enviada para personalizar o perfil.',
    xp: 10,
    reputation: 0,
    repeatability: 'Uma vez por usuario',
    enabled: true,
  },
  {
    key: 'profile_completed',
    eventName: 'profile_completed',
    category: 'Perfil',
    label: 'Perfil completo',
    description: 'Dados principais completos no perfil.',
    xp: 40,
    reputation: 1,
    repeatability: 'Uma vez por usuario',
    enabled: true,
  },
  {
    key: 'legal_article_read',
    eventName: 'legal_article_read',
    category: 'Lei comentada',
    label: 'Artigo lido',
    description: 'Leitura de artigo novo na lei comentada.',
    xp: 2,
    reputation: 0,
    repeatability: 'Uma vez por artigo',
    enabled: true,
  },
  {
    key: 'legal_reading_progress_milestone',
    eventName: 'legal_reading_progress_milestone',
    category: 'Lei comentada',
    label: 'Marcos de leitura',
    description: 'Marcos de 25%, 50%, 75% e 100% de leitura.',
    xp: 10,
    maxXp: 50,
    reputation: 1,
    repeatability: 'Por marco da lei',
    enabled: true,
  },
  {
    key: 'legal_favorite_added',
    eventName: 'legal_favorite_added',
    category: 'Lei comentada',
    label: 'Favorito na lei',
    description: 'Item da lei salvo para revisao posterior.',
    xp: 3,
    reputation: 0,
    repeatability: 'Por item favoritado',
    enabled: true,
  },
  {
    key: 'legal_comment_submitted',
    eventName: 'legal_comment_submitted',
    category: 'Lei comentada',
    label: 'Comentario na lei',
    description: 'Comentario enviado dentro da lei comentada.',
    xp: 4,
    reputation: 0,
    repeatability: 'Por comentario',
    enabled: true,
  },
  {
    key: 'ranking_participation',
    eventName: 'ranking_participation',
    category: 'Ranking pos-prova',
    label: 'Participacao em ranking',
    description: 'Entrada registrada no ranking pos-prova.',
    xp: 20,
    reputation: 0,
    repeatability: 'Uma vez por ranking',
    enabled: true,
  },
  {
    key: 'ranking_approved',
    eventName: 'ranking_approved',
    category: 'Ranking pos-prova',
    label: 'Ranking criado aprovado',
    description: 'Ranking comunitario aprovado pela moderacao.',
    xp: 25,
    reputation: 1,
    repeatability: 'Por ranking aprovado',
    enabled: true,
  },
  {
    key: 'ranking_official_result',
    eventName: 'ranking_official_result',
    category: 'Ranking pos-prova',
    label: 'Resultado oficial do ranking',
    description: 'Premio conforme colocacao apos gabarito oficial.',
    xp: 10,
    maxXp: 60,
    reputation: 3,
    repeatability: 'Por ranking consolidado',
    enabled: true,
  },
  {
    key: 'marketplace_purchase_completed',
    eventName: 'marketplace_purchase_completed',
    category: 'Marketplace',
    label: 'Compra de material',
    description: 'Primeira compra de material no marketplace.',
    xp: 25,
    reputation: 0,
    repeatability: 'Por compra',
    enabled: true,
  },
  {
    key: 'marketplace_sale_completed',
    eventName: 'marketplace_sale_completed',
    category: 'Marketplace',
    label: 'Venda de material',
    description: 'Venda feita por parceiro ou vendedor.',
    xp: 50,
    reputation: 2,
    repeatability: 'Por venda',
    enabled: true,
  },
  {
    key: 'marketplace_material_approved',
    eventName: 'marketplace_material_approved',
    category: 'Marketplace',
    label: 'Material aprovado',
    description: 'Material aprovado pela curadoria.',
    xp: 30,
    reputation: 1,
    repeatability: 'Por material aprovado',
    enabled: true,
  },
];

export const DEFAULT_NOTIFICATION_RULES: NotificationRuleSettings[] = [
  {
    key: 'welcome',
    category: 'Conta',
    label: 'Boas-vindas',
    trigger: 'Quando o usuario cria ou confirma a conta.',
    title: 'Bem-vindo ao ConcursoMestre!',
    message: 'Mensagem inicial de boas-vindas e orientacao da plataforma.',
    type: 'success',
    link: '/dashboard',
    enabled: true,
  },
  {
    key: 'account_activated',
    category: 'Conta',
    label: 'Conta ativada',
    trigger: 'Quando o e-mail ou cadastro e ativado.',
    title: 'Conta ativada com sucesso!',
    message: 'Confirma que a conta foi ativada e o aluno ja pode usar a plataforma.',
    type: 'success',
    link: '/dashboard',
    enabled: true,
  },
  {
    key: 'referral_reward',
    category: 'Conta',
    label: 'Recompensa por indicacao',
    trigger: 'Quando uma indicacao passa da carencia e libera recompensa.',
    title: 'Recompensa por indicacao liberada!',
    message: 'Uma indicacao liberou dias adicionais no plano e XP.',
    type: 'success',
    link: '/profile?tab=referral',
    enabled: true,
  },
  {
    key: 'badge_unlocked',
    category: 'Gamificacao',
    label: 'Badge desbloqueado',
    trigger: 'Quando um badge e conquistado.',
    title: 'Badge desbloqueado',
    message: 'Mensagem dinamica com o badge conquistado.',
    type: 'success',
    link: '/profile?tab=achievements',
    enabled: true,
  },
  {
    key: 'level_bonus',
    category: 'Gamificacao',
    label: 'Bonus por nivel',
    trigger: 'Quando o aluno sobe de nivel.',
    title: 'Bonus de nivel alcancado!',
    message: 'Parabens! Por subir de nivel, voce ganhou dias extras de acesso.',
    type: 'success',
    link: '/profile?tab=billing',
    enabled: true,
  },
  {
    key: 'xp_bonus',
    category: 'Gamificacao',
    label: 'Bonus de XP',
    trigger: 'Quando um marco de XP e desbloqueado.',
    title: 'Bonus de XP desbloqueado',
    message: 'Mensagem dinamica com o marco e a quantidade de XP.',
    type: 'success',
    link: '/levels',
    enabled: true,
  },
  {
    key: 'study_streak',
    category: 'Gamificacao',
    label: 'Sequencia de estudos',
    trigger: 'Quando o aluno mantem uma sequencia relevante.',
    title: 'Sequencia de estudos',
    message: 'Voce manteve uma sequencia de estudos.',
    type: 'success',
    link: '/profile?tab=achievements',
    enabled: true,
  },
  {
    key: 'question_saved',
    category: 'Questoes',
    label: 'Questao salva',
    trigger: 'Quando o aluno salva uma questao para revisar.',
    title: 'Questao salva',
    message: 'Voce ganhou +3 XP por salvar uma questao para revisar.',
    type: 'success',
    link: '/practice',
    enabled: true,
  },
  {
    key: 'simulation_completed',
    category: 'Simulados',
    label: 'Simulado concluido',
    trigger: 'Quando um simulado e concluido.',
    title: 'Simulado concluido',
    message: 'Seu simulado rendeu XP conforme volume e acertos.',
    type: 'success',
    link: '/simulation',
    enabled: true,
  },
  {
    key: 'comment_pending_admin',
    category: 'Comunidade',
    label: 'Comentario aguardando moderacao',
    trigger: 'Quando um comentario precisa de revisao da equipe.',
    title: 'Comentario aguardando moderacao',
    message: 'Um comentario foi enviado e precisa de moderacao.',
    type: 'warning',
    link: '/admin/support/comments',
    enabled: true,
  },
  {
    key: 'comment_submitted',
    category: 'Comunidade',
    label: 'Comentario enviado',
    trigger: 'Quando o aluno envia um comentario que ainda precisa de moderacao.',
    title: 'Comentario enviado',
    message: 'Seu comentario foi enviado para moderacao. Voce ganhou XP pela contribuicao.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'comment_reply',
    category: 'Comunidade',
    label: 'Resposta em comentario',
    trigger: 'Quando o aluno responde um comentario.',
    title: 'Resposta publicada',
    message: 'Sua resposta foi registrada. Voce ganhou XP por participar da comunidade.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'comment_approved',
    category: 'Comunidade',
    label: 'Comentario aprovado',
    trigger: 'Quando a moderacao aprova um comentario.',
    title: 'Comentario aprovado',
    message: 'Seu comentario foi aprovado e ja esta visivel na plataforma.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'comment_published',
    category: 'Comunidade',
    label: 'Comentario publicado',
    trigger: 'Quando o comentario fica visivel automaticamente.',
    title: 'Comentario publicado',
    message: 'Seu comentario ficou visivel. Voce ganhou XP pela contribuicao.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'community_xp',
    category: 'Comunidade',
    label: 'XP de comunidade',
    trigger: 'Quando um comentario aprovado rende XP extra.',
    title: 'XP de comunidade',
    message: 'Seu comentario aprovado pela moderacao rendeu XP.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'comment_like_received',
    category: 'Comunidade',
    label: 'Curtida recebida',
    trigger: 'Quando outro aluno curte um comentario.',
    title: 'Curtida recebida',
    message: 'Seu comentario recebeu uma curtida. Voce ganhou XP e reputacao.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'report_received',
    category: 'Moderacao',
    label: 'Denuncia recebida',
    trigger: 'Quando o aluno envia uma denuncia.',
    title: 'Denuncia recebida',
    message: 'Recebemos sua denuncia. Voce ganhou XP pela contribuicao inicial.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'report_accepted',
    category: 'Moderacao',
    label: 'Denuncia aceita',
    trigger: 'Quando a equipe aceita uma denuncia.',
    title: 'Denuncia aceita',
    message: 'Sua denuncia foi aceita. Motivo da decisao informado pela equipe.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'moderation_xp',
    category: 'Moderacao',
    label: 'XP de moderacao',
    trigger: 'Quando uma denuncia procedente rende XP.',
    title: 'XP de moderacao',
    message: 'Sua denuncia procedente rendeu XP e reputacao.',
    type: 'success',
    link: '/notifications',
    enabled: true,
  },
  {
    key: 'profile_updated',
    category: 'Perfil',
    label: 'Foto de perfil',
    trigger: 'Quando o usuario adiciona foto ao perfil.',
    title: 'Perfil atualizado',
    message: 'Voce ganhou +10 XP por adicionar uma foto ao perfil.',
    type: 'success',
    link: '/profile?tab=achievements',
    enabled: true,
  },
  {
    key: 'profile_completed',
    category: 'Perfil',
    label: 'Perfil completo',
    trigger: 'Quando o perfil atinge os dados principais completos.',
    title: 'Perfil completo',
    message: 'Voce ganhou +40 XP por completar seus dados principais.',
    type: 'success',
    link: '/profile?tab=achievements',
    enabled: true,
  },
  {
    key: 'platform_rating',
    category: 'Suporte',
    label: 'Avaliacao recebida',
    trigger: 'Quando o aluno avalia a plataforma.',
    title: 'Avaliacao recebida',
    message: 'Obrigado pela avaliacao. Voce ganhou XP por ajudar a plataforma.',
    type: 'success',
    link: '/support',
    enabled: true,
  },
  {
    key: 'suggestion_received',
    category: 'Suporte',
    label: 'Sugestao recebida',
    trigger: 'Quando o aluno envia uma sugestao publica.',
    title: 'Sugestao recebida',
    message: 'Sua sugestao entrou no mural. Voce ganhou XP por contribuir.',
    type: 'success',
    link: '/support',
    enabled: true,
  },
  {
    key: 'support_opened',
    category: 'Suporte',
    label: 'Atendimento aberto',
    trigger: 'Quando o aluno abre atendimento comum.',
    title: 'Atendimento aberto',
    message: 'Recebemos sua mensagem. Voce ganhou XP por interagir com a plataforma.',
    type: 'success',
    link: '/support',
    enabled: true,
  },
  {
    key: 'support_reply',
    category: 'Suporte',
    label: 'Resposta registrada',
    trigger: 'Quando o aluno responde uma conversa de suporte.',
    title: 'Resposta registrada',
    message: 'Voce ganhou XP por manter a conversa de suporte atualizada.',
    type: 'success',
    link: '/support',
    enabled: true,
  },
  {
    key: 'suggestion_vote',
    category: 'Suporte',
    label: 'Voto em sugestao',
    trigger: 'Quando o aluno vota em sugestao publica.',
    title: 'Voto registrado',
    message: 'Seu voto ajudou a priorizar melhorias da comunidade.',
    type: 'success',
    link: '/support?category=feedback',
    enabled: true,
  },
  {
    key: 'legal_favorite',
    category: 'Lei comentada',
    label: 'Favorito salvo',
    trigger: 'Quando o aluno favorita item da lei comentada.',
    title: 'Favorito salvo',
    message: 'Voce ganhou XP por organizar sua revisao na lei comentada.',
    type: 'success',
    link: '/lei-comentada',
    enabled: true,
  },
  {
    key: 'legal_progress',
    category: 'Lei comentada',
    label: 'Progresso na lei comentada',
    trigger: 'Quando o aluno alcanca marco de leitura.',
    title: 'Progresso na lei comentada',
    message: 'Voce chegou a um marco de leitura e ganhou XP.',
    type: 'success',
    link: '/lei-comentada',
    enabled: true,
  },
  {
    key: 'legal_comment',
    category: 'Lei comentada',
    label: 'Comentario enviado',
    trigger: 'Quando o aluno comenta na lei comentada.',
    title: 'Comentario enviado',
    message: 'Seu comentario na lei comentada foi enviado para moderacao. Voce ganhou XP.',
    type: 'success',
    link: '/lei-comentada',
    enabled: true,
  },
  {
    key: 'ranking_joined',
    category: 'Rankings',
    label: 'Participacao registrada',
    trigger: 'Quando o aluno entra no ranking pos-prova.',
    title: 'Participacao registrada',
    message: 'Seu gabarito foi registrado no ranking.',
    type: 'success',
    link: '/ranking',
    enabled: true,
  },
  {
    key: 'official_key_published',
    category: 'Rankings',
    label: 'Gabarito oficial publicado',
    trigger: 'Quando o gabarito oficial de um ranking e publicado.',
    title: 'Gabarito oficial publicado',
    message: 'O gabarito oficial do ranking foi publicado.',
    type: 'info',
    link: '/ranking',
    enabled: true,
  },
  {
    key: 'renewal_reminder',
    category: 'Assinatura',
    label: 'Renovacao automatica',
    trigger: 'Quando uma assinatura esta proxima da renovacao.',
    title: 'Renovacao automatica em 5 dias',
    message: 'Sua proxima renovacao esta prevista em breve. Revise valor e cartao salvo.',
    type: 'info',
    link: '/profile/billing',
    enabled: true,
  },
  {
    key: 'renewal_tomorrow',
    category: 'Assinatura',
    label: 'Plano renova amanha',
    trigger: 'Quando a renovacao automatica esta prevista para o dia seguinte.',
    title: 'Seu plano renovara amanha',
    message: 'Aviso de renovacao para manter acesso premium sem interrupcao.',
    type: 'info',
    link: '/profile/billing',
    enabled: true,
  },
  {
    key: 'refund_requested',
    category: 'Assinatura',
    label: 'Reembolso solicitado',
    trigger: 'Quando o aluno solicita reembolso de uma compra.',
    title: 'Reembolso solicitado',
    message: 'Sua solicitacao de reembolso foi registrada e esta em analise.',
    type: 'info',
    link: '/profile?tab=billing',
    enabled: true,
  },
  {
    key: 'material_submitted',
    category: 'Marketplace',
    label: 'Material enviado',
    trigger: 'Quando um vendedor envia material para revisao.',
    title: 'Material enviado para revisao',
    message: 'Seu material foi enviado e aguarda analise da equipe.',
    type: 'info',
    link: '/partner',
    enabled: true,
  },
  {
    key: 'material_pending_admin',
    category: 'Marketplace',
    label: 'Material aguardando moderacao',
    trigger: 'Quando a equipe precisa revisar um novo material.',
    title: 'Material aguardando moderacao',
    message: 'Um vendedor enviou material para revisao.',
    type: 'warning',
    link: '/admin/marketplace/materials',
    enabled: true,
  },
  {
    key: 'material_approved',
    category: 'Marketplace',
    label: 'Material aprovado',
    trigger: 'Quando a curadoria aprova material.',
    title: 'Material aprovado',
    message: 'Seu material foi aprovado e ja esta disponivel na loja.',
    type: 'success',
    link: '/marketplace',
    enabled: true,
  },
  {
    key: 'material_rejected',
    category: 'Marketplace',
    label: 'Material rejeitado',
    trigger: 'Quando a curadoria rejeita material.',
    title: 'Material rejeitado',
    message: 'Seu material foi rejeitado com o motivo informado pela equipe.',
    type: 'error',
    link: '/partner',
    enabled: true,
  },
  {
    key: 'material_removed',
    category: 'Marketplace',
    label: 'Material removido',
    trigger: 'Quando um material e removido administrativamente.',
    title: 'Material removido',
    message: 'Seu material foi removido da plataforma pela administracao.',
    type: 'error',
    link: '/partner',
    enabled: true,
  },
  {
    key: 'material_released',
    category: 'Marketplace',
    label: 'Material liberado',
    trigger: 'Quando o pagamento de material e aprovado.',
    title: 'Material liberado',
    message: 'Pagamento confirmado. O material ja esta disponivel na biblioteca.',
    type: 'success',
    link: '/profile?tab=materials',
    enabled: true,
  },
  {
    key: 'marketplace_sale',
    category: 'Marketplace',
    label: 'Nova venda',
    trigger: 'Quando um vendedor realiza venda no marketplace.',
    title: 'Nova venda no marketplace',
    message: 'Um aluno comprou o material. O valor liquido estimado e informado.',
    type: 'success',
    link: '/partner',
    enabled: true,
  },
  {
    key: 'finance_transaction_created',
    category: 'Financeiro',
    label: 'Nova transacao',
    trigger: 'Quando uma compra, assinatura ou renovacao vira transacao real.',
    title: 'Nova transacao financeira',
    message: 'O financeiro recebe o resumo da transacao confirmada.',
    type: 'success',
    link: '/admin/finance/transactions',
    enabled: true,
  },
  {
    key: 'marketplace_purchase_admin',
    category: 'Marketplace',
    label: 'Compra confirmada para admin',
    trigger: 'Quando uma compra de material e confirmada.',
    title: 'Compra de material confirmada',
    message: 'Resumo administrativo da compra confirmada no marketplace.',
    type: 'success',
    link: '/admin/finance/transactions',
    enabled: true,
  },
];

export const DEFAULT_GAMIFICATION_SETTINGS: GamificationSettings = {
  enabled: true,
  rules: DEFAULT_GAMIFICATION_RULES,
};

export const DEFAULT_NOTIFICATION_SETTINGS: NotificationSettings = {
  enabled: true,
  rules: DEFAULT_NOTIFICATION_RULES,
};

export const normalizeGamificationSettings = (
  incoming?: Partial<GamificationSettings> | null,
): GamificationSettings => {
  const payload = incoming && typeof incoming === 'object' ? incoming : {};
  const incomingRules = Array.isArray(payload.rules) ? payload.rules : [];
  const incomingByKey = new Map(
    incomingRules
      .filter((rule) => rule && typeof rule === 'object' && typeof rule.key === 'string')
      .map((rule) => [rule.key, rule as Partial<GamificationRuleSettings>]),
  );

  const rules = DEFAULT_GAMIFICATION_RULES.map((defaultRule) => {
    const incomingRule = incomingByKey.get(defaultRule.key) || {};
    return {
      ...defaultRule,
      enabled: normalizeBoolean(incomingRule.enabled, defaultRule.enabled),
      xp: Number.isFinite(Number(incomingRule.xp)) ? Number(incomingRule.xp) : defaultRule.xp,
      maxXp: incomingRule.maxXp === undefined
        ? defaultRule.maxXp
        : (Number.isFinite(Number(incomingRule.maxXp)) ? Number(incomingRule.maxXp) : defaultRule.maxXp),
      reputation: Number.isFinite(Number(incomingRule.reputation)) ? Number(incomingRule.reputation) : defaultRule.reputation,
    };
  });

  return {
    enabled: normalizeBoolean(payload.enabled, DEFAULT_GAMIFICATION_SETTINGS.enabled),
    rules,
    updatedAt: typeof payload.updatedAt === 'string' ? payload.updatedAt : undefined,
  };
};

export const normalizeNotificationSettings = (
  incoming?: Partial<NotificationSettings> | null,
): NotificationSettings => {
  const payload = incoming && typeof incoming === 'object' ? incoming : {};
  const incomingRules = Array.isArray(payload.rules) ? payload.rules : [];
  const incomingByKey = new Map(
    incomingRules
      .filter((rule) => rule && typeof rule === 'object' && typeof rule.key === 'string')
      .map((rule) => [rule.key, rule as Partial<NotificationRuleSettings>]),
  );

  const rules = DEFAULT_NOTIFICATION_RULES.map((defaultRule) => {
    const incomingRule = incomingByKey.get(defaultRule.key) || {};
    return {
      ...defaultRule,
      label: typeof incomingRule.label === 'string' ? incomingRule.label : defaultRule.label,
      trigger: typeof incomingRule.trigger === 'string' ? incomingRule.trigger : defaultRule.trigger,
      title: typeof incomingRule.title === 'string' ? incomingRule.title : defaultRule.title,
      message: typeof incomingRule.message === 'string' ? incomingRule.message : defaultRule.message,
      type: typeof incomingRule.type === 'string' && incomingRule.type.trim() ? incomingRule.type.trim() : defaultRule.type,
      link: incomingRule.link === null
        ? null
        : (typeof incomingRule.link === 'string' ? incomingRule.link.trim() : defaultRule.link),
      audience: typeof incomingRule.audience === 'string' && incomingRule.audience.trim() ? incomingRule.audience.trim() : defaultRule.audience,
      enabled: normalizeBoolean(incomingRule.enabled, defaultRule.enabled),
    };
  });

  return {
    enabled: normalizeBoolean(payload.enabled, DEFAULT_NOTIFICATION_SETTINGS.enabled),
    rules,
    updatedAt: typeof payload.updatedAt === 'string' ? payload.updatedAt : undefined,
  };
};
