import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { ContentHeader } from '@/features/content/components/ContentHeader';
import { findDeck } from '@/features/content/contentData';
import { radius, spacing, typography } from '@/theme/tokens';
import { useAppTheme } from '@/theme/useAppTheme';

export default function FlashcardStudyScreen() {
  const theme = useAppTheme(); const { id } = useLocalSearchParams<{ id: string }>(); const deck = findDeck(id || ''); const [index, setIndex] = React.useState(0); const [flipped, setFlipped] = React.useState(false);
  if (!deck) return <View style={[styles.empty, { backgroundColor: theme.background }]}><Text style={{ color: theme.text }}>Baralho não encontrado.</Text></View>;
  const card = deck.cards[index]; const next = (correct: boolean) => { setFlipped(false); setIndex((value) => value + 1 < deck.cards.length ? value + 1 : 0); };
  return <View style={[styles.screen, { backgroundColor: theme.background }]}><ContentHeader title={deck.title} subtitle={`${index + 1} de ${deck.cards.length} cartões`} /><ScrollView contentContainerStyle={styles.content}><View style={[styles.progressTrack, { backgroundColor: theme.surfaceSubtle }]}><View style={[styles.progress, { backgroundColor: theme.primary, width: `${((index + 1) / deck.cards.length) * 100}%` }]} /></View><Pressable accessibilityRole="button" onPress={() => setFlipped((value) => !value)} style={[styles.card, { backgroundColor: theme.surface, borderColor: theme.border }]}><Ionicons name={flipped ? 'checkmark-circle-outline' : 'help-circle-outline'} size={28} color={theme.primary} /><Text style={[styles.cardLabel, { color: theme.textMuted }]}>{flipped ? 'RESPOSTA' : 'PERGUNTA'}</Text><Text style={[styles.cardText, { color: theme.text }]}>{flipped ? card.back : card.front}</Text><Text style={[styles.tapHint, { color: theme.textMuted }]}>Toque para virar</Text></Pressable><View style={styles.actions}><Pressable onPress={() => next(false)} style={[styles.action, { backgroundColor: theme.dangerSubtle }]}><Ionicons name="close" size={20} color={theme.danger} /><Text style={{ color: theme.danger }}>Errei</Text></Pressable><Pressable onPress={() => next(true)} style={[styles.action, { backgroundColor: theme.successSubtle }]}><Ionicons name="checkmark" size={20} color={theme.success} /><Text style={{ color: theme.success }}>Acertei</Text></Pressable></View></ScrollView></View>;
}
const styles = StyleSheet.create({ screen: { flex: 1 }, empty: { alignItems: 'center', flex: 1, justifyContent: 'center' }, content: { gap: spacing[5], padding: spacing[5] }, progressTrack: { borderRadius: radius.pill, height: 8, overflow: 'hidden' }, progress: { borderRadius: radius.pill, height: '100%' }, card: { alignItems: 'center', borderRadius: radius.xl, borderWidth: 1, gap: spacing[3], justifyContent: 'center', minHeight: 340, padding: spacing[6] }, cardLabel: { fontSize: typography.size.xs, fontWeight: typography.weight.bold, letterSpacing: 1 }, cardText: { fontSize: typography.size.xl, fontWeight: typography.weight.semibold, lineHeight: 30, textAlign: 'center' }, tapHint: { fontSize: typography.size.xs }, actions: { flexDirection: 'row', gap: spacing[3] }, action: { alignItems: 'center', borderRadius: radius.md, flex: 1, flexDirection: 'row', gap: spacing[2], justifyContent: 'center', padding: spacing[4] } });
