/*
* ----------------------------------------------------
* @author: 4quarenta
* @author URI: https://github.com/4quarenta
* @copyright: (c) 2026 ConcursoMestre. All rights reserved
* ----------------------------------------------------
*
* @since 1.0.0
*
*/

import type {
  ArticleExamTip,
  ArticleJurisprudence,
  LawArticle,
  LawDetail,
  LawSummary,
  LawUpdate,
  LegalArea,
  LegalSyncLog,
  TeacherComment,
} from '@types';

export const LEGAL_RECENT_UPDATE_WINDOW_DAYS = 45;

export const legalAreasSeed: LegalArea[] = [
  {
    id: 'area-constitucional',
    catalogId: 'constitucional',
    slug: 'constitucional',
    name: 'Constitucional',
    colorClass: 'text-blue-600',
    iconName: 'Scale',
    totalLaws: 1,
    description: 'Constituição, direitos fundamentais, organização do Estado e controle de constitucionalidade.',
    order: 1,
    iconTone: 'indigo',
  },
  {
    id: 'area-penal',
    catalogId: 'penal',
    slug: 'penal',
    name: 'Penal',
    colorClass: 'text-destructive',
    iconName: 'Gavel',
    totalLaws: 2,
    description: 'Parte geral, crimes em espécie, leis penais especiais e execução penal.',
    order: 2,
    iconTone: 'rose',
  },
  {
    id: 'area-administrativo',
    catalogId: 'administrativo',
    slug: 'administrativo',
    name: 'Administrativo',
    colorClass: 'text-emerald-600',
    iconName: 'Landmark',
    totalLaws: 3,
    description: 'Agentes públicos, licitações, improbidade, processo administrativo e controle.',
    order: 3,
    iconTone: 'emerald',
  },
  {
    id: 'area-civil',
    catalogId: 'civil',
    slug: 'civil',
    name: 'Civil',
    colorClass: 'text-amber-600',
    iconName: 'BookOpen',
    totalLaws: 1,
    description: 'LINDB, Código Civil, obrigações, contratos, responsabilidade civil e família.',
    order: 4,
    iconTone: 'amber',
  },
  {
    id: 'area-tributario',
    catalogId: 'tributario',
    slug: 'tributario',
    name: 'Tributário',
    colorClass: 'text-cyan-600',
    iconName: 'Receipt',
    totalLaws: 1,
    description: 'CTN, limitações ao poder de tributar, crédito tributário e execução fiscal.',
    order: 5,
    iconTone: 'cyan',
  },
  {
    id: 'area-processual',
    catalogId: 'processual',
    slug: 'processual',
    name: 'Processual',
    colorClass: 'text-violet-600',
    iconName: 'Layers',
    totalLaws: 1,
    description: 'Processo civil, processo penal, recursos, provas e procedimentos.',
    order: 6,
    iconTone: 'violet',
  },
  {
    id: 'area-legislacao-especial',
    catalogId: 'legislacao-especial',
    slug: 'legislacao-especial',
    name: 'Legislação Especial',
    totalLaws: 1,
    description: 'Leis cobradas de forma recorrente em carreiras policiais, tribunais e áreas transversais.',
    order: 7,
    iconTone: 'slate',
  },
  {
    id: 'area-direitos-humanos',
    catalogId: 'direitos-humanos',
    slug: 'direitos-humanos',
    name: 'Direitos Humanos',
    totalLaws: 0,
    description: 'Tratados, convenções e normas protetivas relevantes para concursos.',
    order: 8,
    iconTone: 'sky',
  },
];

export const lawsSeed: LawSummary[] = [
  {
    id: 'law-cf-88',
    catalogId: 'cf-1988',
    slug: 'constituicao-federal-1988',
    areaId: 'area-constitucional',
    acronym: 'CF/88',
    title: 'Constituição da República Federativa do Brasil de 1988',
    shortTitle: 'Constituição Federal',
    number: 'CRFB/1988',
    year: '1988',
    description: 'Constituição da República Federativa do Brasil',
    date: '1988-10-05',
    aliases: ['CF/88', 'Constituição Federal', 'Carta Magna'],
    summary: 'Texto constitucional base para direitos fundamentais, organização do Estado e Administração Pública.',
    ementa: 'Promulgada em 5 de outubro de 1988, é a lei fundamental e suprema do Brasil.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:00:00.000Z',
    lastUpdatedAt: '2026-04-10T12:00:00.000Z',
    isRecentlyUpdated: true,
    articleCount: 250,
    commentedArticleCount: 180,
    jurisprudenceCount: 9,
    examTipCount: 12,
    accessCount: 18420,
  },
  {
    id: 'law-cp',
    catalogId: 'cp',
    slug: 'codigo-penal',
    areaId: 'area-penal',
    acronym: 'CP',
    title: 'Código Penal',
    shortTitle: 'Código Penal',
    number: 'Decreto-Lei 2.848',
    year: '1940',
    description: 'Código Penal Brasileiro',
    date: '1940-12-07',
    aliases: ['CP', 'Decreto-Lei 2.848'],
    summary: 'Código Penal Brasileiro',
    ementa: 'Decreto-Lei nº 2.848, de 7 de dezembro de 1940. Institui o Código Penal.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/CCIVIL_03/Decreto-Lei/Del2848compilado.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:05:00.000Z',
    lastUpdatedAt: '2026-03-30T10:30:00.000Z',
    isRecentlyUpdated: true,
    articleCount: 361,
    commentedArticleCount: 220,
    jurisprudenceCount: 15,
    examTipCount: 16,
    accessCount: 14330,
  },
  {
    id: 'law-cpp',
    catalogId: 'cpp',
    slug: 'codigo-processo-penal',
    areaId: 'area-processual',
    acronym: 'CPP',
    title: 'Código de Processo Penal',
    shortTitle: 'Código de Processo Penal',
    number: 'Decreto-Lei 3.689/1941',
    year: '1941',
    description: 'Código de Processo Penal',
    date: '1941-10-03',
    aliases: ['CPP', 'Processo Penal'],
    summary: 'Inquérito, ação penal, provas, prisões, recursos e procedimentos penais.',
    ementa: 'Decreto-Lei nº 3.689, de 3 de outubro de 1941.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/decreto-lei/Del3689compilado.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:10:00.000Z',
    lastUpdatedAt: '2026-04-01T11:00:00.000Z',
    isRecentlyUpdated: true,
    articleCount: 811,
    commentedArticleCount: 19,
    jurisprudenceCount: 14,
    examTipCount: 13,
    accessCount: 10320,
  },
  {
    id: 'law-cc',
    catalogId: 'cc',
    slug: 'codigo-civil',
    areaId: 'area-civil',
    acronym: 'CC',
    title: 'Código Civil',
    shortTitle: 'Código Civil',
    number: 'Lei 10.406/2002',
    year: '2002',
    description: 'Código Civil Brasileiro',
    date: '2002-01-10',
    aliases: ['CC', 'Lei 10.406'],
    summary: 'Pessoas, bens, fatos jurídicos, obrigações, contratos, responsabilidade civil e família.',
    ementa: 'Lei nº 10.406, de 10 de janeiro de 2002. Institui o Código Civil.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:15:00.000Z',
    isRecentlyUpdated: false,
    articleCount: 2046,
    commentedArticleCount: 14,
    jurisprudenceCount: 7,
    examTipCount: 9,
    accessCount: 8420,
  },
  {
    id: 'law-8112',
    catalogId: 'lei-8112',
    slug: 'lei-8112',
    areaId: 'area-administrativo',
    acronym: 'Lei 8.112/90',
    title: 'Regime Jurídico dos Servidores Públicos Civis da União',
    shortTitle: 'Lei 8.112/90',
    number: 'Lei 8.112/1990',
    year: '1990',
    description: 'Estatuto dos Servidores Públicos Civis da União',
    date: '1990-12-11',
    aliases: ['Estatuto dos Servidores', 'Lei 8112'],
    summary: 'Direitos, deveres, responsabilidades e regime disciplinar dos servidores públicos federais.',
    ementa: 'Dispõe sobre o regime jurídico dos servidores públicos civis da União, das autarquias e das fundações públicas federais.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/leis/l8112cons.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:20:00.000Z',
    isRecentlyUpdated: false,
    articleCount: 253,
    commentedArticleCount: 11,
    jurisprudenceCount: 5,
    examTipCount: 10,
    accessCount: 9150,
  },
  {
    id: 'law-14133',
    catalogId: 'lei-14133',
    slug: 'nova-lei-licitacoes',
    areaId: 'area-administrativo',
    acronym: 'Lei 14.133/21',
    title: 'Lei de Licitações e Contratos Administrativos',
    shortTitle: 'Lei 14.133/21',
    number: 'Lei 14.133/2021',
    year: '2021',
    description: 'Lei de Licitações e Contratos Administrativos',
    date: '2021-04-01',
    aliases: ['Nova Lei de Licitações', 'NLLC'],
    summary: 'Normas gerais de licitação e contratação para Administrações Públicas diretas, autárquicas e fundacionais.',
    ementa: 'Estabelece normas gerais de licitação e contratação para as Administrações Públicas.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:25:00.000Z',
    lastUpdatedAt: '2026-04-03T13:00:00.000Z',
    isRecentlyUpdated: true,
    articleCount: 194,
    commentedArticleCount: 16,
    jurisprudenceCount: 4,
    examTipCount: 13,
    accessCount: 13200,
  },
  {
    id: 'law-ctn',
    catalogId: 'ctn',
    slug: 'codigo-tributario-nacional',
    areaId: 'area-tributario',
    acronym: 'CTN',
    title: 'Código Tributário Nacional',
    shortTitle: 'CTN',
    number: 'Lei 5.172/1966',
    year: '1966',
    description: 'Código Tributário Nacional',
    date: '1966-10-25',
    aliases: ['CTN', 'Lei 5.172'],
    summary: 'Sistema Tributário Nacional e normas gerais de direito tributário aplicáveis à União, Estados e Municípios.',
    ementa: 'Dispõe sobre o Sistema Tributário Nacional e institui normas gerais de direito tributário.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/leis/l5172compilado.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:30:00.000Z',
    isRecentlyUpdated: false,
    articleCount: 218,
    commentedArticleCount: 9,
    jurisprudenceCount: 6,
    examTipCount: 7,
    accessCount: 6740,
  },
  {
    id: 'law-improbidade',
    catalogId: 'lei-improbidade',
    slug: 'lei-improbidade-administrativa',
    areaId: 'area-administrativo',
    acronym: 'LIA',
    title: 'Lei de Improbidade Administrativa',
    shortTitle: 'Lei de Improbidade',
    number: 'Lei 8.429/1992',
    year: '1992',
    description: 'Lei de Improbidade Administrativa',
    date: '1992-06-02',
    aliases: ['LIA', 'Lei 8429'],
    summary: 'Atos de improbidade, sanções, ação de improbidade e efeitos das alterações recentes.',
    ementa: 'Dispõe sobre as sanções aplicáveis em virtude da prática de atos de improbidade administrativa.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/leis/l8429.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:35:00.000Z',
    isRecentlyUpdated: false,
    articleCount: 26,
    commentedArticleCount: 8,
    jurisprudenceCount: 5,
    examTipCount: 6,
    accessCount: 6120,
  },
  {
    id: 'law-maria-penha',
    catalogId: 'lei-maria-da-penha',
    slug: 'lei-maria-da-penha',
    areaId: 'area-legislacao-especial',
    acronym: 'Lei 11.340/06',
    title: 'Lei Maria da Penha',
    shortTitle: 'Lei Maria da Penha',
    number: 'Lei 11.340/2006',
    year: '2006',
    description: 'Lei Maria da Penha',
    date: '2006-08-07',
    aliases: ['Violência Doméstica', 'Lei 11340'],
    summary: 'Mecanismos para coibir violência doméstica e familiar contra a mulher.',
    ementa: 'Cria mecanismos para coibir a violência doméstica e familiar contra a mulher.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11340.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:40:00.000Z',
    isRecentlyUpdated: false,
    articleCount: 46,
    commentedArticleCount: 8,
    jurisprudenceCount: 5,
    examTipCount: 6,
    accessCount: 7210,
  },
  {
    id: 'law-lep',
    catalogId: 'lep',
    slug: 'lei-execucao-penal',
    areaId: 'area-penal',
    acronym: 'LEP',
    title: 'Lei de Execução Penal',
    shortTitle: 'Lei de Execução Penal',
    number: 'Lei 7.210/1984',
    year: '1984',
    description: 'Lei de Execução Penal',
    date: '1984-07-11',
    aliases: ['LEP', 'Lei 7210'],
    summary: 'Execução das penas, direitos do preso, regimes, benefícios e órgãos da execução penal.',
    ementa: 'Institui a Lei de Execução Penal.',
    status: 'active',
    officialUrl: 'https://www.planalto.gov.br/ccivil_03/leis/l7210.htm',
    sourceName: 'Portal do Planalto',
    lastSyncedAt: '2026-04-18T09:45:00.000Z',
    isRecentlyUpdated: false,
    articleCount: 204,
    commentedArticleCount: 10,
    jurisprudenceCount: 5,
    examTipCount: 8,
    accessCount: 5870,
  },
];

export const lawArticlesSeed: LawArticle[] = [
  {
    id: 'art-cf-1',
    lawId: 'law-cf-88',
    slug: 'art-1',
    number: '1º',
    title: 'Dos Princípios Fundamentais',
    text: 'A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos:',
    paragraphs: [
      { number: 'I', text: 'a soberania;' },
      { number: 'II', text: 'a cidadania;' },
      { number: 'III', text: 'a dignidade da pessoa humana;' },
      { number: 'IV', text: 'os valores sociais do trabalho e da livre iniciativa;' },
      { number: 'V', text: 'o pluralismo político.' },
    ],
    doctrine: [
      'José Afonso da Silva: a dignidade da pessoa humana é valor supremo que atrai o conteúdo de todos os direitos fundamentais.',
      'Ingo Sarlet: trata-se de princípio matriz, com dupla dimensão negativa e prestacional.',
    ],
    examTip: 'SO-CI-DI-VA-PLU: soberania, cidadania, dignidade, valores sociais do trabalho e pluralismo político.',
    relatedQuestionCount: 142,
    hierarchy: { title: 'Dos Princípios Fundamentais' },
    blocks: [
      { id: 'art-cf-1-caput', kind: 'caput', label: 'Caput', text: 'A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos:' },
    ],
    officialAnchor: '#art1',
  },
  {
    id: 'art-cf-2',
    lawId: 'law-cf-88',
    slug: 'art-2',
    number: '2º',
    title: 'Separação dos Poderes',
    text: 'São Poderes da União, independentes e harmônicos entre si, o Legislativo, o Executivo e o Judiciário.',
    examTip: 'A Constituição fala em Poderes independentes e harmônicos entre si. A troca por "ou" costuma tornar a alternativa incorreta.',
    relatedQuestionCount: 87,
    hierarchy: { title: 'Dos Princípios Fundamentais' },
    blocks: [
      { id: 'art-cf-2-caput', kind: 'caput', label: 'Caput', text: 'São Poderes da União, independentes e harmônicos entre si, o Legislativo, o Executivo e o Judiciário.' },
    ],
    officialAnchor: '#art2',
  },
  {
    id: 'art-cf-5',
    lawId: 'law-cf-88',
    slug: 'art-5',
    number: '5º',
    title: 'Direitos e Garantias Fundamentais',
    text: 'Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.',
    jurisprudenceNotes: [
      'STF — RE 587.970: estrangeiros não residentes também possuem direitos fundamentais assegurados.',
    ],
    syllabi: [
      { court: 'STF', number: 'Vinculante 11', text: 'Só é lícito o uso de algemas em casos de resistência e de fundado receio de fuga ou de perigo à integridade física própria ou alheia.' },
      { court: 'STJ', number: '568', text: 'O relator pode decidir monocraticamente quando houver entendimento dominante acerca do tema.' },
    ],
    doctrine: [
      'Alexandre de Moraes: o rol do art. 5º é exemplificativo, admitindo direitos implícitos e decorrentes de tratados.',
    ],
    examTip: 'Caput: vida, liberdade, igualdade, segurança e propriedade.',
    relatedQuestionCount: 312,
    hierarchy: { title: 'Dos Direitos e Garantias Fundamentais', chapter: 'Dos Direitos e Deveres Individuais e Coletivos' },
    blocks: [
      { id: 'art-cf-5-caput', kind: 'caput', label: 'Caput', text: 'Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.' },
      { id: 'art-cf-5-ii', kind: 'inciso', label: 'II', text: 'Ninguém será obrigado a fazer ou deixar de fazer alguma coisa senão em virtude de lei.' },
      { id: 'art-cf-5-liv', kind: 'inciso', label: 'LIV', text: 'Ninguém será privado da liberdade ou de seus bens sem o devido processo legal.' },
    ],
    officialAnchor: '#art5',
  },
  {
    id: 'art-cf-37',
    lawId: 'law-cf-88',
    slug: 'art-37',
    number: '37',
    title: 'Administração Pública',
    hierarchy: { title: 'Da Organização do Estado', chapter: 'Da Administração Pública' },
    isRecentlyChanged: true,
    blocks: [
      { id: 'art-cf-37-caput', kind: 'caput', label: 'Caput', text: 'A administração pública direta e indireta obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.', isRecentlyChanged: true, previousText: 'Redação anterior monitorada na versão precedente.' },
      { id: 'art-cf-37-ii', kind: 'inciso', label: 'II', text: 'A investidura em cargo ou emprego público depende de aprovação prévia em concurso público de provas ou de provas e títulos.' },
    ],
    officialAnchor: '#art37',
  },
  {
    id: 'art-cp-1',
    lawId: 'law-cp',
    slug: 'art-1',
    number: '1º',
    title: 'Anterioridade da lei',
    text: 'Não há crime sem lei anterior que o defina. Não há pena sem prévia cominação legal.',
    examTip: "'Não há crime sem lei anterior' = princípio da legalidade (nullum crimen sine lege).",
    relatedQuestionCount: 198,
    hierarchy: { title: 'Da Aplicação da Lei Penal' },
    blocks: [
      { id: 'art-cp-1-caput', kind: 'caput', label: 'Caput', text: 'Não há crime sem lei anterior que o defina. Não há pena sem prévia cominação legal.' },
    ],
    officialAnchor: '#art1',
  },
  {
    id: 'art-cp-121',
    lawId: 'law-cp',
    slug: 'art-121',
    number: '121',
    title: 'Homicídio',
    text: 'Matar alguém: Pena - reclusão, de seis a vinte anos.',
    paragraphs: [
      {
        number: '§1º',
        text: 'Se o agente comete o crime impelido por motivo de relevante valor social ou moral, ou sob o domínio de violenta emoção, logo em seguida a injusta provocação da vítima, o juiz pode reduzir a pena de um sexto a um terço.',
      },
      {
        number: '§2º',
        text: 'Se o homicídio é cometido: I - mediante paga ou promessa de recompensa, ou por outro motivo torpe... Pena - reclusão, de doze a trinta anos.',
      },
    ],
    jurisprudenceNotes: [
      'STJ — REsp 1.234.567: dolo eventual em homicídio no trânsito exige prova robusta da assunção do risco.',
    ],
    syllabi: [
      { court: 'STJ', number: '610', text: 'O homicídio qualificado é hediondo, ainda que praticado na forma tentada.' },
      { court: 'STF', number: '603', text: 'A competência para o processo e julgamento de latrocínio é do juiz singular e não do Tribunal do Júri.' },
    ],
    doctrine: [
      'Rogério Greco: o homicídio é o crime que atinge o bem jurídico mais importante — a vida humana extrauterina.',
      'Cleber Masson: a qualificadora do feminicídio tem natureza objetiva (condição da mulher).',
    ],
    examTip: 'Pena base 6-20 anos. Qualificado 12-30 anos. Privilegiado: redução de 1/6 a 1/3.',
    relatedQuestionCount: 256,
    hierarchy: { title: 'Dos Crimes contra a Pessoa', chapter: 'Dos Crimes contra a Vida' },
    blocks: [
      { id: 'art-cp-121-caput', kind: 'caput', label: 'Caput', text: 'Matar alguém: Pena - reclusão, de seis a vinte anos.' },
    ],
    officialAnchor: '#art121',
  },
  {
    id: 'art-cp-14',
    lawId: 'law-cp',
    slug: 'art-14',
    number: '14',
    title: 'Crime consumado e tentado',
    hierarchy: { title: 'Do Crime' },
    blocks: [
      { id: 'art-cp-14-i', kind: 'inciso', label: 'I', text: 'Consumado, quando nele se reúnem todos os elementos de sua definição legal.' },
      { id: 'art-cp-14-ii', kind: 'inciso', label: 'II', text: 'Tentado, quando, iniciada a execução, não se consuma por circunstâncias alheias à vontade do agente.' },
      { id: 'art-cp-14-pu', kind: 'paragraph', label: 'Parágrafo único', text: 'Salvo disposição em contrário, pune-se a tentativa com a pena correspondente ao crime consumado, diminuída de um a dois terços.' },
    ],
    officialAnchor: '#art14',
  },
  {
    id: 'art-cpp-312',
    lawId: 'law-cpp',
    slug: 'art-312',
    number: '312',
    title: 'Prisão preventiva',
    hierarchy: { title: 'Da Prisão Preventiva' },
    isRecentlyChanged: true,
    blocks: [
      { id: 'art-cpp-312-caput', kind: 'caput', label: 'Caput', text: 'A prisão preventiva poderá ser decretada como garantia da ordem pública, da ordem econômica, por conveniência da instrução criminal ou para assegurar a aplicação da lei penal.', isRecentlyChanged: true, previousText: 'Trecho sinalizado para comparação com a redação anterior após sincronização.' },
      { id: 'art-cpp-312-p1', kind: 'paragraph', label: '§ 1º', text: 'A prisão preventiva também poderá ser decretada em caso de descumprimento de qualquer das obrigações impostas por força de outras medidas cautelares.' },
    ],
    officialAnchor: '#art312',
  },
  {
    id: 'art-14133-5',
    lawId: 'law-14133',
    slug: 'art-5',
    number: '5º',
    title: 'Princípios das licitações',
    hierarchy: { chapter: 'Dos Princípios' },
    isRecentlyChanged: true,
    blocks: [
      { id: 'art-14133-5-caput', kind: 'caput', label: 'Caput', text: 'Na aplicação desta Lei, serão observados os princípios da legalidade, impessoalidade, moralidade, publicidade, eficiência, interesse público, probidade administrativa, igualdade, planejamento, transparência, eficácia, segregação de funções, motivação, vinculação ao edital, julgamento objetivo, segurança jurídica, razoabilidade, competitividade, proporcionalidade, celeridade, economicidade e desenvolvimento nacional sustentável.', isRecentlyChanged: true, previousText: 'Versão anterior mantida no histórico para comparação editorial.' },
    ],
    officialAnchor: '#art5',
  },
  {
    id: 'art-8112-116',
    lawId: 'law-8112',
    slug: 'art-116',
    number: '116',
    title: 'Deveres do servidor',
    hierarchy: { title: 'Do Regime Disciplinar', chapter: 'Dos Deveres' },
    blocks: [
      { id: 'art-8112-116-caput', kind: 'caput', label: 'Caput', text: 'São deveres do servidor:' },
      { id: 'art-8112-116-i', kind: 'inciso', label: 'I', text: 'Exercer com zelo e dedicação as atribuições do cargo.' },
      { id: 'art-8112-116-iii', kind: 'inciso', label: 'III', text: 'Observar as normas legais e regulamentares.' },
    ],
    officialAnchor: '#art116',
  },
  {
    id: 'art-ctn-3',
    lawId: 'law-ctn',
    slug: 'art-3',
    number: '3º',
    title: 'Conceito de tributo',
    hierarchy: { book: 'Sistema Tributário Nacional' },
    blocks: [
      { id: 'art-ctn-3-caput', kind: 'caput', label: 'Caput', text: 'Tributo é toda prestação pecuniária compulsória, em moeda ou cujo valor nela se possa exprimir, que não constitua sanção de ato ilícito, instituída em lei e cobrada mediante atividade administrativa plenamente vinculada.' },
    ],
    officialAnchor: '#art3',
  },
  {
    id: 'art-mp-5',
    lawId: 'law-maria-penha',
    slug: 'art-5',
    number: '5º',
    title: 'Violência doméstica e familiar',
    hierarchy: { title: 'Da Violência Doméstica e Familiar contra a Mulher' },
    blocks: [
      { id: 'art-mp-5-caput', kind: 'caput', label: 'Caput', text: 'Configura violência doméstica e familiar contra a mulher qualquer ação ou omissão baseada no gênero que lhe cause morte, lesão, sofrimento físico, sexual ou psicológico e dano moral ou patrimonial.' },
    ],
    officialAnchor: '#art5',
  },
  {
    id: 'art-lep-112',
    lawId: 'law-lep',
    slug: 'art-112',
    number: '112',
    title: 'Progressão de regime',
    hierarchy: { title: 'Da Execução das Penas em Espécie' },
    blocks: [
      { id: 'art-lep-112-caput', kind: 'caput', label: 'Caput', text: 'A pena privativa de liberdade será executada em forma progressiva com a transferência para regime menos rigoroso, a ser determinada pelo juiz.' },
    ],
    officialAnchor: '#art112',
  },
];

export const teacherCommentsSeed: TeacherComment[] = [
  {
    id: 'tc-cf-1-1',
    articleId: 'art-cf-1',
    title: 'Fundamentos da República',
    body: 'Este artigo é considerado o pilar do Estado brasileiro. Memorize os fundamentos e dê atenção especial à dignidade da pessoa humana, que costuma aparecer como princípio matriz dos direitos fundamentais.',
    examFocus: ['Fundamentos da República', 'Dignidade da pessoa humana', 'SO-CI-DI-VA-PLU'],
    pitfalls: ['Não confundir fundamentos com objetivos fundamentais do art. 3º.'],
    relatedRefs: ['CF/88, art. 3º', 'CF/88, art. 5º'],
    authorName: 'Prof. Carlos Mendes',
    authorRole: 'Mestre em Direito Constitucional',
    reviewedAt: '2026-04-18T09:55:00.000Z',
  },
  {
    id: 'tc-cf-2-1',
    articleId: 'art-cf-2',
    title: 'Independência e harmonia dos Poderes',
    body: 'O art. 2º consagra a separação dos Poderes. Para concursos, a expressão-chave é "independentes e harmônicos entre si", ligada ao sistema de freios e contrapesos.',
    examFocus: ['Separação dos Poderes', 'Freios e contrapesos', 'Cláusula pétrea'],
    pitfalls: ['A banca costuma trocar "e" por "ou" ou sugerir subordinação entre os Poderes.'],
    relatedRefs: ['CF/88, art. 60, §4º, III'],
    authorName: 'Prof. Carlos Mendes',
    authorRole: 'Mestre em Direito Constitucional',
    reviewedAt: '2026-04-18T09:58:00.000Z',
  },
  {
    id: 'tc-cf-5-1',
    articleId: 'art-cf-5',
    title: 'Direitos fundamentais mais cobrados',
    body: 'O art. 5º é o dispositivo constitucional mais recorrente em questões. O caput traz vida, liberdade, igualdade, segurança e propriedade; o rol é exemplificativo e deve ser lido junto aos tratados de direitos humanos.',
    examFocus: ['Direitos fundamentais', 'Rol exemplificativo', 'Aplicação a estrangeiros'],
    pitfalls: ['Não restrinja a proteção apenas a brasileiros; a jurisprudência amplia a tutela de direitos fundamentais.'],
    relatedRefs: ['CF/88, art. 5º, §2º', 'Tratados internacionais de direitos humanos'],
    authorName: 'Profª. Ana Beatriz',
    authorRole: 'Doutora em Direitos Humanos',
    reviewedAt: '2026-04-18T09:59:00.000Z',
  },
  {
    id: 'tc-cf-37-1',
    articleId: 'art-cf-37',
    title: 'LIMPE e concurso público',
    body: 'O art. 37 é um dos dispositivos mais cobrados em Administrativo e Constitucional. A banca costuma misturar princípios expressos com princípios implícitos e cobrar a regra do concurso público como desdobramento da impessoalidade.',
    examFocus: ['Princípios expressos', 'Concurso público', 'Administração direta e indireta'],
    pitfalls: ['Publicidade não é propaganda pessoal.', 'Eficiência não autoriza violar legalidade.'],
    relatedRefs: ['Lei 8.112/90, art. 116', 'Lei 14.133/21, art. 5º'],
    authorName: 'Equipe Editorial ConcursoMestre',
    reviewedAt: '2026-04-18T10:00:00.000Z',
  },
  {
    id: 'tc-cp-1-1',
    articleId: 'art-cp-1',
    title: 'Princípio da legalidade penal',
    body: 'Princípio da legalidade ou reserva legal (nullum crimen, nulla poena sine lege). Espelha o art. 5º, XXXIX da CF/88. Decorrem dele: anterioridade, taxatividade e proibição da analogia in malam partem.',
    examFocus: ['Legalidade', 'Anterioridade', 'Taxatividade'],
    pitfalls: ['Não confundir analogia in bonam partem com analogia in malam partem.'],
    relatedRefs: ['CF/88, art. 5º, XXXIX'],
    authorName: 'Prof. Roberto Lima',
    authorRole: 'Delegado de Polícia Federal',
    reviewedAt: '2026-04-18T10:03:00.000Z',
  },
  {
    id: 'tc-cp-14-1',
    articleId: 'art-cp-14',
    title: 'Tentativa: início da execução é o ponto decisivo',
    body: 'Para prova, concentre-se na diferença entre atos preparatórios e início da execução. A tentativa exige que o agente comece a executar o núcleo típico e o crime não se consume por circunstâncias alheias à sua vontade.',
    examFocus: ['Iter criminis', 'Tentativa', 'Redução de pena'],
    pitfalls: ['Desistência voluntária não é tentativa.', 'Crime culposo, em regra, não admite tentativa.'],
    relatedRefs: ['Código Penal, art. 15', 'Código Penal, art. 16'],
    authorName: 'Equipe Editorial ConcursoMestre',
    reviewedAt: '2026-04-18T10:05:00.000Z',
  },
  {
    id: 'tc-cp-121-1',
    articleId: 'art-cp-121',
    title: 'Homicídio: o centro da Parte Especial',
    body: 'Crime mais cobrado da Parte Especial. Atenção às qualificadoras (§2º) e ao homicídio privilegiado (§1º). O feminicídio (§2º-A) foi incluído pela Lei 13.104/2015 e é hediondo.',
    examFocus: ['Homicídio simples', 'Homicídio privilegiado', 'Qualificadoras'],
    pitfalls: ['Privilegiado-qualificado exige compatibilidade entre privilégio subjetivo e qualificadora objetiva.'],
    relatedRefs: ['CP, art. 14', 'Lei 8.072/90'],
    authorName: 'Prof. Roberto Lima',
    authorRole: 'Delegado de Polícia Federal',
    reviewedAt: '2026-04-18T10:06:00.000Z',
  },
  {
    id: 'tc-14133-5-1',
    articleId: 'art-14133-5',
    title: 'Princípios novos da Lei 14.133/21',
    body: 'Além dos princípios clássicos, a nova lei trouxe expressamente planejamento, segregação de funções, transparência, eficácia, segurança jurídica e desenvolvimento nacional sustentável. Bancas gostam de perguntar quais estão no texto legal.',
    examFocus: ['Princípios expressos', 'Segregação de funções', 'Planejamento'],
    pitfalls: ['Não confundir julgamento objetivo com discricionariedade livre.', 'Segregação de funções reduz risco de concentração indevida.'],
    relatedRefs: ['CF, art. 37', 'Lei 14.133/21, art. 11'],
    authorName: 'Equipe Editorial ConcursoMestre',
    reviewedAt: '2026-04-18T10:10:00.000Z',
  },
  {
    id: 'tc-ctn-3-1',
    articleId: 'art-ctn-3',
    title: 'Conceito legal de tributo',
    body: 'Memorize os elementos: prestação pecuniária compulsória, em moeda, não sancionatória, instituída por lei e cobrada por atividade vinculada. O ponto mais cobrado é que tributo não é sanção por ato ilícito.',
    examFocus: ['Conceito de tributo', 'Atividade vinculada', 'Sanção x tributo'],
    pitfalls: ['Multa não é tributo.', 'Compulsoriedade não dispensa lei.'],
    relatedRefs: ['CF, art. 145', 'CTN, art. 4º'],
    authorName: 'Equipe Editorial ConcursoMestre',
    reviewedAt: '2026-04-18T10:15:00.000Z',
  },
];

export const jurisprudenceSeed: ArticleJurisprudence[] = [
  {
    id: 'jur-cf-5-stf-1',
    articleId: 'art-cf-5',
    court: 'STF',
    precedentType: 'Tema de repercussão geral',
    title: 'Devido processo legal e contraditório',
    summary: 'O devido processo legal orienta a validade de atos estatais que restrinjam liberdade ou patrimônio.',
    examImpact: 'Em prova, ligue contraditório, ampla defesa e motivação de decisões restritivas.',
    isConsolidated: true,
    priority: 'high',
  },
  {
    id: 'jur-cpp-312-stj-1',
    articleId: 'art-cpp-312',
    court: 'STJ',
    precedentType: 'Jurisprudência em teses',
    title: 'Fundamentação concreta da preventiva',
    summary: 'A prisão preventiva exige fundamentação concreta, não bastando gravidade abstrata do delito.',
    examImpact: 'A alternativa que fundamenta preventiva apenas na gravidade abstrata tende a estar errada.',
    isConsolidated: true,
    priority: 'high',
  },
  {
    id: 'jur-mp-5-stj-1',
    articleId: 'art-mp-5',
    court: 'STJ',
    precedentType: 'Súmula',
    title: 'Aplicação da Lei Maria da Penha',
    summary: 'A jurisprudência prioriza a proteção integral da mulher em contexto doméstico e familiar.',
    examImpact: 'Atenção ao vínculo doméstico, familiar ou íntimo de afeto e à motivação de gênero.',
    isConsolidated: true,
    priority: 'high',
  },
];

export const examTipsSeed: ArticleExamTip[] = [
  {
    id: 'tip-cf-37-limpe',
    articleId: 'art-cf-37',
    title: 'Macete para prova',
    body: 'LIMPE: Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência. Se a banca trouxer razoabilidade ou proporcionalidade como princípio expresso do caput, desconfie.',
    tags: ['LIMPE', 'Princípios'],
  },
  {
    id: 'tip-cp-14-tentativa',
    articleId: 'art-cp-14',
    title: 'Macete para prova',
    body: 'Tentativa = começou a executar + não consumou + causa alheia à vontade. Se parou por vontade própria, pense em desistência voluntária.',
    tags: ['Tentativa', 'Iter criminis'],
  },
  {
    id: 'tip-ctn-3-tributo',
    articleId: 'art-ctn-3',
    title: 'Macete para prova',
    body: 'Tributo nunca é punição. Multa pune; tributo arrecada ou regula.',
    tags: ['Tributo', 'Multa'],
  },
];

export const lawUpdatesSeed: LawUpdate[] = [
  {
    id: 'upd-cf-37-2026-04',
    lawId: 'law-cf-88',
    articleId: 'art-cf-37',
    changedAt: '2026-04-10T12:00:00.000Z',
    changeType: 'changed',
    title: 'Atualização monitorada no art. 37',
    summary: 'Dispositivo sinalizado pelo monitor para revisão editorial após alteração legislativa recente.',
    previousText: 'Redação anterior preservada no histórico de versões.',
    currentText: 'Redação atual capturada do Portal do Planalto.',
    sourceUrl: 'https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm',
    examImpact: 'Revisar princípios e regras de acesso a cargos públicos, pois são temas recorrentes.',
  },
  {
    id: 'upd-14133-5-2026-04',
    lawId: 'law-14133',
    articleId: 'art-14133-5',
    changedAt: '2026-04-03T13:00:00.000Z',
    changeType: 'changed',
    title: 'Revisão de princípios da Lei 14.133/21',
    summary: 'Sincronização identificou redação monitorada para controle editorial.',
    previousText: 'Versão anterior arquivada para comparação.',
    currentText: 'Versão atual sincronizada com a fonte oficial.',
    sourceUrl: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm',
    examImpact: 'Princípios expressos são cobrados em questões literais.',
  },
];

export const syncLogsSeed: LegalSyncLog[] = [
  {
    id: 'sync-2026-04-18',
    status: 'success',
    startedAt: '2026-04-18T09:00:00.000Z',
    finishedAt: '2026-04-18T09:50:00.000Z',
    message: 'Monitoramento diário executado para leis prioritárias.',
    insertedArticles: 0,
    changedArticles: 2,
    revokedArticles: 0,
  },
];

export const buildLawDetailSeed = (law: LawSummary): LawDetail | null => {
  const area = legalAreasSeed.find((item) => item.id === law.areaId);
  if (!area) return null;

  return {
    ...law,
    area,
    ementa: law.ementa || law.summary,
    articles: lawArticlesSeed.filter((article) => article.lawId === law.id),
    teacherComments: teacherCommentsSeed,
    jurisprudence: jurisprudenceSeed,
    examTips: examTipsSeed,
    userComments: [],
    updates: lawUpdatesSeed.filter((update) => update.lawId === law.id),
  };
};
